=== Lazyapply/umh/TW/P3/ejemplo/3/basedatos6.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
		  <xsd:element name="basedatos" type="tipobasedatos"/>
		  
		  <xsd:complexType name="tipobasedatos">
		       <xsd:choice minOccurs="1" maxOccurs="unbounded">
		           <xsd:element name="empleado" type="tipoempleado"/>
	           	   <xsd:element name="departamento" type="tipodepartamento"/>
		        </xsd:choice>
		  </xsd:complexType>
		   
		     
		   <xsd:complexType name="tipoempleado">
		      <xsd:sequence>
		         <xsd:element name="num_emp" type="xsd:integer"/>
		         <xsd:element name="nom_emp" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>
		         <xsd:element name="sueldo" type="xsd:float"/>
				 <xsd:element name="num_dep" type="xsd:string"/>
		      </xsd:sequence>
		   </xsd:complexType>
		   
		   		   
		     <xsd:complexType name="tipodepartamento">
		     <xsd:sequence>
			   <xsd:element name="num_dep" type="xsd:string"/>
		       <xsd:element name="nom_dep" type="xsd:string"/>
		       <xsd:element name="presupuesto" type="xsd:integer" minOccurs="0" maxOccurs="1"/>
		       </xsd:sequence>
		   </xsd:complexType>
		   
		  </xsd:schema>

=== Lazyapply/umh/TW/P3/ejemplo/3/new6.xml
<?xml version="1.0" standalone="yes" ?>
<?xml-stylesheet type="text/css" href="a.css"?>

<basedatos  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="basedatos6.xsd" 
xmlns:xlink="http://www.w3.org/1999/xlink">

  <empleado> 
	<num_emp>1</num_emp>	
	<nom_emp>pepe</nom_emp>		
	<sueldo>1000</sueldo>			
	<num_dep>1A</num_dep>	
  </empleado>
  <empleado>
	<num_emp>2</num_emp>	
	<nom_emp>ana</nom_emp>		
	<sueldo>2000</sueldo>			
	<num_dep></num_dep>	
  </empleado>
  <empleado>
	<num_emp>3</num_emp>	
	<nom_emp>rosa</nom_emp>		
	<nom_emp>rosae</nom_emp>		
	<sueldo>2000</sueldo>			
	<num_dep>2A</num_dep>	
  </empleado>    
  <empleado>
	<num_emp>4</num_emp>	
	<nom_emp>emilio</nom_emp>		
	<sueldo>3000</sueldo>			
	<num_dep>2A</num_dep>	
  </empleado>  
  <departamento>
	<num_dep>1A</num_dep>	
	<nom_dep>contabilidad</nom_dep>		
	<presupuesto>5000</presupuesto>			
  </departamento>
  <departamento>
	<num_dep>2A</num_dep>	
	<nom_dep>i+d</nom_dep>		
	<presupuesto>100000</presupuesto>			
  </departamento>     

</basedatos>
